# Generated by Django 5.2.3 on 2025-06-19 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermsModel',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('term_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
