# Generated by Django 4.1.7 on 2024-07-08 08:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='termsmodel',
            name='term_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
