# Generated by Django 5.2.3 on 2025-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='Course_Videos/'),
        ),
    ]
