# Generated by Django 4.1.7 on 2024-06-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0024_courses_paid_courses_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default.jpg', upload_to='profile_Images'),
        ),
    ]
