# Generated by Django 4.1.7 on 2024-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0028_alter_courses_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
