# Generated by Django 4.1.7 on 2024-07-08 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0029_alter_courses_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='video_file',
            field=models.FileField(blank=True, upload_to='Course_Videos/'),
        ),
    ]
