# Generated by Django 4.1.7 on 2024-07-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0033_alter_team_options_team_date_join'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='courses_enroll',
        ),
        migrations.AddField(
            model_name='profile',
            name='courses_enroll',
            field=models.ManyToManyField(blank=True, null=True, related_name='Enrolled_courses', to='Base.courses'),
        ),
    ]
