# Generated by Django 4.1.7 on 2024-08-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0034_alter_team_options_remove_profile_courses_enroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='courses_enroll',
            field=models.ManyToManyField(blank=True, related_name='Enrolled_courses', to='Base.courses'),
        ),
    ]
