# Generated by Django 4.1.7 on 2025-01-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0035_profile_occupation_alter_profile_courses_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('term_body', models.TextField()),
            ],
        ),
    ]
