# Generated by Django 5.2.3 on 2025-06-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0036_terms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-date_join']},
        ),
    ]
